services:
  app:
    build: .
    container_name: securecrud-app
    depends_on:
      - mongo
    networks:
      - securecrud-net

  mongo:
    image: mongo
    container_name: securecrud-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - securecrud-net

  nginx:
    image: nginx:alpine
    container_name: securecrud-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - securecrud-net

networks:
  securecrud-net:

volumes:
  mongo-data: